#!/usr/bin/env bash
# configures a new Ubuntu machine
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) /n
# using curl, it must return a page that contains the string Hello World!
# You can’t use systemctl for restarting nginx

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > index.html
sudo mv index.html  /var/www/html

# Restart Nginx without systemctl
killall -s HUP nginx
