#!/usr/bin/env bash
# redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
# You answer file should be a Bash script containing commands to automatically
# configure a Ubuntu machine to respect above requirements
# Using what you did with 1-install_nginx_web_server,
# write 3-redirection so that it configures a brand new Ubuntu machine
# to the requirements asked in this task

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
