#!/usr/bin/env bash
# /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
# You answer file should be a Bash script containing commands to automatically
# configure a Ubuntu machine to respect above requirements
# Using what you did with 1-install_nginx_web_server,
# write 3-redirection so that it configures a brand new Ubuntu machine
# to the requirements asked in this task

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sudo apt-get update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
sudo service nginx restart
