#!/usr/bin/env bash
# Configures your Nginx server to have a custom 404 page
# the page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Using what you did with 3-redirection, write 4-not_found_page_404 so that
#it configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get update
sudo apt install -y nginx

echo "Hello World!" > index.html
sudo mv index.html /var/www/html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        internal;
    }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
