#!/usr/bin/env bash
# Configures your Nginx server to have a custom 404 page
# the page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Using what you did with 3-redirection, write 4-not_found_page_404 so that
#it configures a brand new Ubuntu machine to the requirements asked in this task

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"
location_error="location = /404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n"
error_directive="error_page 404 /404.html;\n\t$location_error"
error_404="}\n\n\t$error_directive\t}"

sudo apt-get update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
sudo sed -i "0,/}/ s|}|$error_404|" /etc/nginx/sites-available/default
sudo service nginx restart
