#!/usr/bin/env bash
# Configures your Nginx server to be similar to server web01

sudo apt-get update
sudo apt install -y nginx

echo "Hello World!" > index.html
sudo mv index.html /var/www/html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        internal;
    }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart

config_file="/etc/nginx/nginx.conf"

if ! sudo grep -q "add_header X-Served-By" $config_file;
then
    header_key="X-Served-By"
    header_value="\$hostname"
    header="add_header $header_key $header_value;"
    search="http {"
    new_conf="$search\n\t$header"

    # Replace the value found with the new configuration
    sudo sed -i "s|$search|$new_conf|" $config_file

    # Restart Nginx Service
    sudo service nginx restart
fi
