#!/usr/bin/env bash
# uses ssh to connect to a server using the private key
# Set the path to the private key
KEY=~/.ssh/school

# Set the user and host
USER=ubuntu
HOST=54.84.2.1

# Connect to the server using ssh
ssh -i $KEY $USER@$HOST
